CREATE TABLE IF NOT EXISTS BLOG_TEMPLATE(
    ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CONTENT MEDIUMTEXT NOT NULL,
    NAME VARCHAR(500),
    PATTERN VARCHAR(500),
    CREATETIME DATETIME NOT NULL,
    MODIFYTIME DATETIME,
    ENABLE BOOLEAN DEFAULT FALSE NOT NULL,
    DESCRIPTION VARCHAR(255),
    ALLOWCOMMENT BOOLEAN DEFAULT FALSE NOT NULL
); 

CREATE TABLE IF NOT EXISTS BLOG_BLACKIP(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	IP VARCHAR(50) NOT NULL
);  

CREATE TABLE IF NOT EXISTS BLOG_COMMENT(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    PARENT INT DEFAULT NULL,
    PARENTPATH VARCHAR(255) NOT NULL,
    NICKNAME VARCHAR(20) DEFAULT NULL,
    EMAIL VARCHAR(255) DEFAULT NULL,
    IP VARCHAR(255) NOT NULL,
    ADMIN TINYINT DEFAULT '0' NOT NULL,
    CONTENT VARCHAR(2000) NOT NULL,
    MODULE_ID INT NOT NULL,
    CREATETIME DATETIME NOT NULL,
    MODIFYTIME DATETIME,
    WEBSITE VARCHAR(255) DEFAULT NULL,
    GRAVATAR VARCHAR(255) DEFAULT NULL,
    MODULE_NAME VARCHAR(50) NOT NULL,
    CHECKING TINYINT DEFAULT '0' NOT NULL
);  

CREATE TABLE IF NOT EXISTS BLOG_MOMENT(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CONTENT VARCHAR(4000) NOT NULL ,
    ISPRIVATE TINYINT DEFAULT '0' NOT NULL,
    ALLOWCOMMENT TINYINT DEFAULT '1' NOT NULL,
    TIME DATETIME NOT NULL,
    MODIFYTIME DATETIME DEFAULT NULL,
    HITS INT DEFAULT 0 NOT NULL,
    PASSWORD VARCHAR(50)
); 

CREATE TABLE IF NOT EXISTS BLOG_CATEGORY(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    CREATETIME DATETIME NOT NULL,
    MODIFYTIME DATETIME
);   

CREATE TABLE IF NOT EXISTS BLOG_TAG(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    CREATETIME DATETIME NOT NULL,
    MODIFYTIME DATETIME
);    
CREATE TABLE IF NOT EXISTS BLOG_ARTICLE_TAG(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ARTICLEID INT NOT NULL,
    TAGID INT NOT NULL
);    
CREATE TABLE IF NOT EXISTS BLOG_ARTICLE_CATEGORY(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ARTICLEID INT NOT NULL,
    CATEGORYID INT NOT NULL
);  

CREATE TABLE IF NOT EXISTS BLOG_ARTICLE(
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CONTENT MEDIUMTEXT NOT NULL,
    PUBDATE DATETIME DEFAULT NULL,
    LASTMODIFYDATE DATETIME DEFAULT NULL,
    TITLE VARCHAR(200) NOT NULL,
    ISPRIVATE TINYINT DEFAULT '0' NOT NULL,
    HITS INT DEFAULT '0' NOT NULL,
    SUMMARY VARCHAR(3000),
    LEVEL INT NOT NULL,
    PASSWORD VARCHAR(40) DEFAULT NULL,
    ALIAS VARCHAR(200) DEFAULT NULL,
    ALLOWCOMMENT TINYINT DEFAULT '1' NOT NULL,
    STATUS TINYINT DEFAULT 0 NOT NULL,
    ISDELETED BOOLEAN DEFAULT FALSE NOT NULL,
    FEATUREIMAGE VARCHAR(200)
);  